### ISSUE TITLE
Incorrect @apollo/client package dependency

### ISSUE THREAD

**Issue by mpo-dev** [kamilkisiela/apollo-angular#1811]
**Describe the bug**

Using the library `apollo-client@4.0.1` causes the following build error when using a `@apollo/client` package version below v3.4.0, despite the apollo-client library requiring the `"@apollo/client": "^3.0.0"`.

```
node_modules/apollo-angular/query-ref.d.ts:19:65 - error TS2344: Type 'T' does not satisfy the constraint 'keyof K'.
19     fetchMore<K = V>(fetchMoreOptions: FetchMoreQueryOptions<K, T>): Promise<ApolloQueryResult<T>>;
```

**To Reproduce**

Try to build a project with package versions as in my environment.

**Expected behavior**

The project to build correcty.

**Environment:**
```
- @angular/cli@14.0.4
- @angular/core@14.0.4
- @apollo/client@3.3.21
- apollo-angular@4.0.1
- graphql@15.8.0
- typescript@4.7.4
```

**Comment by Destreyf** [comment]
@mpo-dev I am using apollo-angular@4.0.1 and able to build successfully, my versions are as follows:

```
├── @angular/cli@14.2.1
├── @angular/common@14.2.0
├── @angular/core@14.2.0
├── @apollo/client@3.6.9
├── apollo-angular@4.0.1
├── graphql@16.6.0
├── typescript@4.7.4
```

I would maybe try upgrading your @apollo/client to the latest version `3.6.9` and trying again.

**Comment by mpo-dev** [comment]
@Destreyf That's the point, I figured `apollo-angular@4.0.1` needs at least `"@apollo/client": "^3.4.0"` by trail and error, despite the library dependency specifying  `"@apollo/client": "^3.0.0"`. Any `@apollo/client` version below `3.4.0` results in build errors.

**Comment by pawelpiotrowski** [comment]
I can observe similar (same?) error when using apollo-angular 4.2.0 with @apollo/client 3.7.6. Note: it works fine with 3.7.5.

Working:

`"@angular/core": "^15.1.2",
...
    "@apollo/client": "^3.7.5",
    "apollo-angular": "^4.2.0",`

Not Working:

`"@angular/core": "^15.1.2",
...
    "@apollo/client": "^3.7.6",
    "apollo-angular": "^4.2.0",`

Error:
<img width="1200" alt="Screenshot 2023-02-01 at 10 51 36" src="https://user-images.githubusercontent.com/909792/216023124-8c12dbf8-4ec1-4e32-bc3f-f6de7718878f.png">

**Comment by pawelpiotrowski** [comment]
👆 Seems to be tracked here: https://github.com/kamilkisiela/apollo-angular/pull/1906

**Comment by ArtistaDu** [comment]
I'm getting the same error... how can I update the apollo client using npm?

**Comment by etsraphael** [comment]
Same issue here

**Comment by PowerKiKi** [comment]
Should be solved by #1910, released as 4.2.1.
